name: Keep Replit Alive

on:
  schedule:
    - cron: "*/2 * * * *"   # 2分おき
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit 1
        run: |
          curl -m 10 https://replit.com/@tokudome217/levelbot || true

      - name: Ping Replit 2
        run: |
          curl -m 10 https://replit.com/@tokudome217/mpie_bot || true
                - name: Ping Replit 1
